title: AI Conference Deadlines # (Maintained by @abhshkdz)
# email: abhshkdz@vt.edu
description: Countdowns to top CV/NLP/ML/Robotics/AI conference deadlines
author: duguyue100

baseurl: "https://dgyblog.com/ai-deadlines"

twitter_username: duguyue100
twitter_hashtag: machinelearning
github_username: duguyue100
github_repo: ai-deadlines

markdown: kramdown
ga_id: UA-36274081-2
