title: AI Conference Deadlines # (Maintained by @abhshkdz)
description: Countdowns to top CV/NLP/ML/Robotics/AI conference deadlines
author: duguyue100

domain: "dgyblog.com/ai-deadlines"
baseurl: "https://dgyblog.com/ai-deadlines"

twitter_username: duguyue100
twitter_hashtag: machinelearning
github_username: duguyue100
github_repo: ai-deadlines

markdown: kramdown
